geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'


urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>', adminapp.products, name='products'),
    path('products/read/<int:pk>', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('registration/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('admin_stuff/', include('adminapp.urls', namespace='admin_stuff')),

    path('', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name = 'order_delete'),
    path('product/<int:pk>/price/', ordersapp.get_product_price, name = 'get_product_price'),
]

geekshop/geekshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product



def index(request):
    # products = Product.objects.all()[:4]
    products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')[:4]

    # basket = []
    # if request.user.is_authenticated:
    #     basket = Basket.objects.filter(user=request.user)

    context = {
        'title': 'главная',
        'products': products,
        # 'basket': basket,
    }


    return render(request, 'geekshop/index.html', context)



def contacts(request):
    # basket = []
    # if request.user.is_authenticated:
    #     basket = Basket.objects.filter(user=request.user)


    context = {
        'title': 'контакты',
        # 'basket': basket,
    }

    return render(request, 'geekshop/contact.html', context)

geekshop/geekshop/templates/geekshop/includes/footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>

geekshop/geekshop/templates/geekshop/includes/header.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if request == '/' %}active{% endif %}">домой</a></li>
        <li><a href="{% url 'products:index' %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}">контакты</a></li>
        {% if user.is_authenticated %}
            <li class="dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <a>{{ user.first_name|default:'Пользователь' }}</a>
            </li>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1" style="width: 150px !important;">
                <li>
                    <a class="dropdown-item" href="{% url 'auth:edit' %}">
                        Профиль</a>
                </li>
                <li>
                    <a class="dropdown-item" href="{% url 'orders:orders_list' %}">
                        Заказы</a>
                </li>
                {% if user.is_superuser %}
                    <li><a class="dropdown-item" href="{% url 'admin_stuff:users' %}">Админка</a>
                    </li>
                {% endif %}
                {% if basket %}
                    <li><a class="dropdown-item" href="{% url 'basket:view' %}">Корзина</a>
                    </li>
                {% endif %}
                <li>
                    {% if user.is_authenticated %}
                        <a href="{% url 'auth:logout' %}">выйти</a>
                    {% endif %}
                </li>
            </ul>

            {% if basket %}
                <span>
                    {{ basket.0.total_cost|floatformat:0 }} руб.
                    ({{ basket.0.total_quantity }} шт.)
                </span>
            {% endif %}

        {% endif %}
        {% if not user.is_authenticated %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </ul>
    <a href="#" class="search"></a>
</div>