geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('registration/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('admin_stuff/', include('adminapp.urls', namespace='admin_stuff')),

    path('', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'


urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/page/<int:page>/', products, name='page'),
    path('<int:pk>/', product, name='detail'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64, unique=True
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True
    )

    def __str__(self):
        return f'{self.id} - {self.name}'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128
    )

    image = models.ImageField(
        upload_to='products_images',
        blank=True
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=60,
        blank=True
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True
    )

    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True
    )

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_item():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404

from mainapp.models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.conf import settings
from django.views.decorators.cache import cache_page, never_cache


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category {pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product {pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = 'products_in_category_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk).order_by('price')

    return same_products


@cache_page(3600)
def products(request, pk=None, page=1):
    title = "Каталог"
    links_menu = get_links_menu()
    products = get_products_ordered_by_price()

    if pk is not None:
        if pk == 0:
            products = get_products_ordered_by_price()
            category = {'name': 'все'}
        else:
            category = get_category(pk)
            products = get_products_in_category_ordered_by_price(pk)

        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
        }

        return render(request, 'mainapp/products.html', context)

    hot_product = get_hot_product()
    same_product = get_same_products(hot_product)

    paginator = Paginator(products, 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products_paginator,
        'hot_product': hot_product,
        'same_products': same_product,
    }

    return render(request, 'mainapp/products.html', context=context)

@never_cache
def product(request, pk):
    title = "детали продукта"
    links_menu = get_links_menu()
    product = get_product(pk)

    hot_product = get_hot_product()
    same_product = get_same_products(hot_product)

    context = {
        'title': title,
        'links_menu': links_menu,
        'product': product,
        'same_products': same_product,
    }

    return render(request, 'mainapp/product.html', context=context)

geekshop/mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
    <div class="hero-white">
        {% include 'geekshop/includes/header.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_menu.html' %}
        <div class="details-products">
                <div class="details-slider">

                    <div class="slider-product">
                        <img src="/media/{{ product.image }}">
                    </div>

                    <div class="slider-control">
                        <div class="block">
                            <a href="#"><img src="/static/geekshop/img/controll.jpg" alt="">
                                <div class="text"></div>
                            </a>
                        </div>

                        <div class="block">
                            <a href="#"><img src="/static/geekshop/img/controll1.jpg" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="/static/geekshop/img/controll2.jpg" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                    </div>

                </div>
            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ short_desc }}
                </div>
            </div>
        </div>

        {% if same_products %}
            <div class="related">
                <div class="title clearfix">
                    <h2>Похожие продукты</h2>
                    <a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
                </div>
                <div class="related-products clearfix">
                    {% for same_product in same_products %}
                        <div class="block">
                            <a href=""><img src="/media/{{ same_product.image }}"
                                            alt="" style="width: 100%;">
                                <div class="text">
                                    <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                                    <h4>{{ same_product.name }}</h4>
                                    <p>{{ same_product.description }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
    <div class="hero-white">
        {% include 'geekshop/includes/header.html' %}
    </div>
    <div>
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <div class="details">
        <div class="details-products">
            {% if hot_product %}
                <div class="details-slider col-5">

                    <div class="slider-product">
                        <img src="/media/{{ hot_product.image }}">
                    </div>

                    <div class="slider-control">
                        <div class="block">
                            <a href="#"><img src="/static/geekshop/img/controll.jpg" alt="">
                                <div class="text"></div>
                            </a>
                        </div>

                        <div class="block">
                            <a href="#"><img src="/static/geekshop/img/controll1.jpg" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="/static/geekshop/img/controll2.jpg" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                    </div>

                </div>
                <div class="description col-5">
                    <h3 class="big-bold">{{ hot_product.name }}</h3>
                    <h3 class="red">горячее предложение</h3>
                    <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                    <a href="{% url 'products:detail' hot_product.pk %}" class="red-button">
                        заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                    <div class="description-text">
                        {{ hot_product.short_desc }}
                    </div>
                </div>
                </div>
            {% endif %}
        <div class="products_list">
            <div class="title clearfix">
                {% if category %}
                    <h2>
                        Категория: "{{ category.name|title }}"
                    </h2>
                {% endif %}
            </div>
        </div>

        <div class="category-products products">

            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:detail' product.pk %}">
                        <img src="/media/{{ product.image }}" alt="product" style="width: 100%;">
                        <div class="text">
                            <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="hover">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'products:page' products.previous_page_number %}">
                        <
                    </a>
                {% endif %}
                <span class="current">
                    страница {{ products.number }} из
                    {{ products.paginator.num_pages }}
                </span>
                {% if products.has_next %}
                    <a href="{% url 'products:page' products.next_page_number %}">
                        >
                    </a>
                {% endif %}
            </div>

        </div>
        {% if same_products %}
            <div class="related row">
                <div class="title clearfix">
                    <h2>Похожие продукты</h2>
                    <a class="explore" href="#">показать все <img src="img/arrow.png" alt=""></a>
                </div>
                <div class="related-products row ">
                    {% for same_product in same_products %}
                        <div class="block">
                            <a href="{% url 'products:detail' same_product.pk %}"><img
                                    src="/media/{{ same_product.image }}"
                                    alt="" style="width: 100%;">
                                <div class="text">
                                    <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                                    <h4>{{ same_product.name }}</h4>
                                    <p>{{ same_product.description }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            </div>
        {% endif %}
{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
<{% extends 'geekshop/base.html' %}
{% load static %}


{% block content %}
		<div class="hero-white">
			{% include 'geekshop/includes/header.html' %}
		</div>
            {% include 'mainapp/includes/inc_menu.html' %}

		<div class="product_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}
                </h2>
            <div>

				{% for product in products %}
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<img src="static/geekshop/img/icon-hover.png" alt="img">
								<h4>{{ product.name }}</h4>
								<p>{{ product.short_desc }} </p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
            </div>

		<div class="clr"></div>

	</div>	



{% endblock %}